---
title: Hydrowashautocare
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
remote_theme: raviriley/agency-jekyll-theme
url: https://www.hydrowashautocare.com
baseurl: "/hydrowashautocare"
email: your-email@example.com
description: Welcome to a new era of car detailing services
author: James B.
locale: en-US
analytics:
  google: 
markdown: kramdown
plugins:
- jekyll-remote-theme
